name: Deploy to Nexus
on:
  workflow_dispatch:
jobs:
  restorePassword:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - shell: bash
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
          OSSR_USERNAME: ${{ secrets.OSSR_USERNAME }}
          OSSR_PASSWORD: ${{ secrets.OSSR_PASSWORD }}
          SONATYPE_STATING_PROFILE_ID: ${{ secrets.SONATYPE_STATING_PROFILE_ID }}
        run: |
          echo "${{ secrets.GPG_FILE }}" > sec.gpg.asc
          gpg -d --passphrase "${{ secrets.GPG_FILE_PSWD }}" --batch sec.gpg.asc > sec.gpg
          bundle exec fastlane deployNexus
